-- CreateEnum
CREATE TYPE "PendingDataType" AS ENUM ('NOME_COMPLETO', 'CPF', 'RG', 'ENDERECO', 'TELEFONE', 'EMAIL', 'DATA_NASCIMENTO', 'NOME_MAE', 'DOC_IDENTIDADE', 'DOC_RESIDENCIA', 'DOC_COMPROVANTE_ENDERECO', 'DOC_COMPROVANTE_EMPRESA', 'DOC_COMPROVANTE_RENDA', 'COMPANY_NAME', 'COMPANY_PRINCIPAL_ACTIVITY');

-- AlterTable
ALTER TABLE "Process" ADD COLUMN     "pendingTypeData" "PendingDataType"[] DEFAULT ARRAY[]::"PendingDataType"[];
