export enum ProcessStatus {
  CREATED = "CREATED",
  PENDING_DATA = "PENDING_DATA",
  PENDING_DOCS = "PENDING_DOCS",
  ANALYZING_DATA = "ANALYZING_DATA",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED"
} 